---
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  become: true
  register: result
  until: 'result.rc == 0'
  retries: 0
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  become: true
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
